export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'
export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST'
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS'
export const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE'

export const COMPLETE_ALL_REQUEST = 'COMPLETE_ALL_REQUEST'
export const COMPLETE_ALL_SUCCESS = 'COMPLETE_ALL_SUCCESS'
export const COMPLETE_ALL_FAILURE = 'COMPLETE_ALL_FAILURE'

export const CLEAR_COMPLETED_REQUEST = 'CLEAR_COMPLETED_REQUEST'
export const CLEAR_COMPLETED_SUCCESS = 'CLEAR_COMPLETED_SUCCESS'
export const CLEAR_COMPLETED_FAILURE = 'CLEAR_COMPLETED_FAILURE'

export const TODO_REQUEST = 'TODO_REQUEST';
export const TODO_SUCCESS = 'TODO_SUCCESS';
export const TODO_FAILURE = 'TODO_FAILURE';
